### PR TITLE
Added Logging interface

### LINKED ISSUE #32: global: add proper logging
Currently, the only logs we have are errors printed to `stderr`. We should have a better and consistent way of logging (e.g. error, info, debug, etc.). We can look at the available libraries and other Kotlin/Spring projects to choose.

### PR DESCRIPTION
**Pull request by MRita443**
Closes #32 

Adds a proper logging interface based on SLF4J API and Logback. Classes that require using the logger should now implement the Logging interface and refer to logger().

# Review checklist
-   [ ] Properly documents API changes in `docs/openapi.yml`
-   [ ] Contains enough appropriate tests
-   [ ] Behavior is as expected
-   [ ] Clean, well structured code

### CODE REVIEW

**Review by BrunoRosendo — APPROVED** [review]
Looks good, simple and clean!

**Review by ttoino — APPROVED** [review]
LGTM!

**Review by bdmendes — COMMENTED** [review]
Looks good! Have you tried the annotation as in https://stackabuse.com/guide-to-logging-in-spring-boot/? What do you think of that vs the interface @BrunoRosendo?

**Review by LuisDuarte1 — COMMENTED** [review]
I agree with @bdmendes because an annotation looks cleaner, in my opinion, and it doesn't use inheritance, even though, `@Slf4j` is not a explicit name and it should be changed to something more straightforward.

**Review by BrunoRosendo — CHANGES_REQUESTED** [review]
> Looks good! Have you tried the annotation as in https://stackabuse.com/guide-to-logging-in-spring-boot/? What do you think of that vs the interface @BrunoRosendo?

I don't have a strong opinion between inheritance and annotation but I'd prefer only having to do 1 import. Right now, we import Logging and then we also import `logger()` because it's an extension function. I think either the annotation or having `logger()` as a field of an abstract class (for example, there might be other ways) would be easier to use

(requested changes for discussion)

**Comment by MRita443** [comment]
I tried the annotation method but I could not get it to work, as recommended [here](https://stackoverflow.com/questions/60419699/implement-slf4j-annotation-from-lombok-in-kotlin) I then tried looking into other idiomatic solutions in Kotlin for better alternatives (more detailed [explanation](https://stackoverflow.com/questions/34416869/idiomatic-way-of-logging-in-kotlin/65195488#65195488)). Here are a few that I liked:

- **Extension function without marking interface:** I initially used a marking interface because the standalone function would lead to the pollution of the any namespace, but that then led to having two imports, we could always remove the marking interface if the pollution would not be of significance;
- **Property Delegates:** A clean solution that would lead to a single import and a line of code of the sorts of `private val logger by LoggerDelegate()` on every class requiring logging;
- **Abstract class:** Another play on my first extension function with marker solution would be to create an abstract class that implements the interface, create a logger variable there, and import just the abstract class instead. A big set back of this would be that the logging messages refer to the abstract class instead of the class where the logger is being called.

Let me know what you guys think and if you have any other suggestions!

**Comment by bdmendes** [comment]
> I tried the annotation method but I could not get it to work, as recommended [here](https://stackoverflow.com/questions/60419699/implement-slf4j-annotation-from-lombok-in-kotlin) I then tried looking into other idiomatic solutions in Kotlin for better alternatives (more detailed [explanation](https://stackoverflow.com/questions/34416869/idiomatic-way-of-logging-in-kotlin/65195488#65195488)). Here are a few that I liked:
> 
>     * **Extension function without marking interface:** I initially used a marking interface because the standalone function would lead to the pollution of the any namespace, but that then led to having two imports, we could always remove the marking interface if the pollution would not be of significance;
> 
>     * **Property Delegates:** A clean solution that would lead to a single import and a line of code of the sorts of `private val logger by LoggerDelegate()` on every class requiring logging;
> 
>     * **Abstract class:** Another play on my first extension function with marker solution would be to create an abstract class that implements the interface, create a logger variable there, and import just the abstract class instead. A big set back of this would be that the logging messages refer to the abstract class instead of the class where the logger is being called.
> 
> 
> Let me know what you guys think and if you have any other suggestions!

Personally, I think that your current solution is cleaner than all of those.
Just a quick suggestion: if I recall correctly, interfaces in Kotlin can have variables as well, so you can save an internal logger on the interface and refer to it every time `logger()` is called instead of calling `getLogger()`.

**Comment by ttoino** [comment]
> > I tried the annotation method but I could not get it to work, as recommended [here](https://stackoverflow.com/questions/60419699/implement-slf4j-annotation-from-lombok-in-kotlin) I then tried looking into other idiomatic solutions in Kotlin for better alternatives (more detailed [explanation](https://stackoverflow.com/questions/34416869/idiomatic-way-of-logging-in-kotlin/65195488#65195488)). Here are a few that I liked:
> > ```
> > * **Extension function without marking interface:** I initially used a marking interface because the standalone function would lead to the pollution of the any namespace, but that then led to having two imports, we could always remove the marking interface if the pollution would not be of significance;
> > 
> > * **Property Delegates:** A clean solution that would lead to a single import and a line of code of the sorts of `private val logger by LoggerDelegate()` on every class requiring logging;
> > 
> > * **Abstract class:** Another play on my first extension function with marker solution would be to create an abstract class that implements the interface, create a logger variable there, and import just the abstract class instead. A big set back of this would be that the logging messages refer to the abstract class instead of the class where the logger is being called.
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Let me know what you guys think and if you have any other suggestions!
> 
> Personally, I think that your current solution is cleaner than all of those. Just a quick suggestion: if I recall correctly, interfaces in Kotlin can have variables as well, so you can save an internal logger on the interface and refer to it every time `logger()` is called instead of calling `getLogger()`.

You could do something like this with only one import:

```kotlin
interface Logging {
    val logger: Logger get() = getLogger(this::class.java)
}
```

Unfortunately you can't assign default values to properties in interfaces, as they are abstract and must be given a value by the implementing class. So something like this **would not** work:

```kotlin
interface Logging {
    val logger = getLogger(this::class.java)
}
```

**Comment by bdmendes** [comment]
In that case, I think the current solution is fine. Let me know what you all think

**Review by BrunoRosendo — APPROVED** [review]
I'm OK with this implementation too

**Review by ttoino — APPROVED** [review]

**Review by Sirze01 — APPROVED** [review]

**Pull request merged**
