### PR TITLE
Integration Tests

### LINKED ISSUE #9: tests: implement integration tests for current endpoints
The goal of this issue is to setup the integration environment we can use in current and following functionalities. I think it'd be best to focus on IT rather than trying to unit test all the layers of the project.

That way, we should be able to mock the server using Spring Boot tools (please check [this tutorial](https://www.youtube.com/watch?v=2e72RHO8ORk&list=PL6gx4Cwl9DGDPsneZWaOFg0H2wsundyGr&index=7)) and test each endpoint however we'd like, e.g, check status code, responses, errors, etc.

### LINKED ISSUE #34: Fix `@RequestBody` vulnerability
The vulnerability can be summarized here: https://rules.sonarsource.com/java/tag/spring/RSPEC-4684

We could implement a proper DTO pattern or use an alternate solution. I'll leave it to discussion

### PR DESCRIPTION
**Pull request by BrunoRosendo**
Closes #9 #34 

Adds integration tests for existing endpoints and some unit tests for other functions

# Review checklist
-   [ ] Properly documents API changes in `docs/openapi.yml`
-   [x] Contains enough appropriate tests
-   [x] Behavior is as expected
-   [x] Clean, well structured code

### CODE REVIEW

**Comment by BrunoRosendo** [comment]
On hold until #27 is fixed. Testing validations is a pain because the binding errors silence them

**Comment by BrunoRosendo** [comment]
> 

#27 will not be fixed, I'll manage the tests

**Comment by BrunoRosendo** [comment]
This is ready but I'll have to wait until #20 and #34 are merged, since the posts updates will be changed and the tests I wrote will work with the new version

**Comment by BrunoRosendo** [comment]
This is fully ready for review @DoStini @limwa @bdmendes :nerd_face:

**Review by ttoino — APPROVED** [review]
LGTM!

The event tests are a little inconsistent when compared to the others, but this can be fixed in #5.

**Comment by BrunoRosendo** [comment]
> LGTM!
> 
> The event tests are a little inconsistent when compared to the others, but this can be fixed in #5.

Can you be a little more specific? Maybe I can fix that in this PR

**Comment by ttoino** [comment]
> > LGTM!
> > The event tests are a little inconsistent when compared to the others, but this can be fixed in #5.
> 
> Can you be a little more specific? Maybe I can fix that in this PR

The function \`should return all events\`() uses a different strategy than the equivalent functions for posts and projects.

**Comment by BrunoRosendo** [comment]
> > > LGTM!
> > > The event tests are a little inconsistent when compared to the others, but this can be fixed in #5.
> > 
> > 
> > Can you be a little more specific? Maybe I can fix that in this PR
> 
> The function `should return all events`() uses a different strategy than the equivalent functions for posts and projects.

You're right! I can fix that

**Review by ttoino — APPROVED** [review]
LGTM! :rocket:

**Pull request merged**
