### PR TITLE
Api/api spec

### LINKED ISSUE #8: api: add api spec to the project
In order to better control and organize our API specification, we should have it documented and maintained, even if the endpoints have not yet been created. The best option is probably OpenAPI but feel free to try something else if you feel like it'd fit best here (a docusaurus documentation could be nice but it's a lot more work and probably overkill)

### PR DESCRIPTION
**Pull request by Sirze01**
Closes #8 

[Description of the changes proposed in the pull request]
Add automatic openapi documentation for the API and the swagger-ui to explore it. 
Check the README for more details.

# Screenshots

swagger-ui

# Review checklist
-   [ ] Properly documents API changes in `docs/openapi.yml`
-   [ ] Contains enough appropriate tests
-   [x] Behavior is as expected
-   [x] Clean, well structured code

If you have some feedback or suggestions please tell me...

### CODE REVIEW

**Comment by Sirze01** [comment]
Looks like my editor had fun with the indentation. I will take care of it as soon as I can. 
Please test the functionality either way.

**Comment by BrunoRosendo** [comment]
> Looks like my editor had fun with the indentation. I will take care of it as soon as I can. Please test the functionality either way.

We have some setup information about linting in the README. Tell us if you need help with that

**Comment by BrunoRosendo** [comment]
I took a look at the implementation and I prefer to discuss it in the weekly meeting :)

**Comment by BrunoRosendo** [comment]
This was discussed in a meeting and we'll try a second approach with spring rest docs

**Pull request closed without merging**
