### PR TITLE
Automatically upload ci artifacts

### LINKED ISSUE #21: ci: automatically upload build scan and other artifacts
When the CI finishes a build (for the `test` workflow), it would be very useful if it uploaded to that build's artifacts some build outputs such as ktlint reports and spring boot reports.
It could also upload a link to a Gradle Build Scan.

This would allow us to debug more easily what is happening on the Actions' servers and correct CI fails faster.

### PR DESCRIPTION
**Pull request by ttoino**
Closes #21.

### CODE REVIEW

**Comment by ttoino** [comment]
For now we're uploading the ktlint and test reports, do you think we should upload anything else? @limwa

**Comment by limwa** [comment]
I was thinking about a Gradle Build Scan report, but that depends on the information present in a failed test report. Do you have any reports (similar to the ones currently uploaded) for test runs that have failed?

**Comment by ttoino** [comment]
[Here is a report with failed tests](https://github.com/NIAEFEUP/website-niaefeup-backend/files/10709034/test.zip)

**Comment by BrunoRosendo** [comment]
This seems promising! But how do you download the reports?

**Comment by ttoino** [comment]
> This seems promising! But how do you download the reports?

You can download them from the actions summary page

image

**Review by BrunoRosendo — APPROVED** [review]
Nice!

**Review by limwa — APPROVED** [review]
Very well done! The reports have all the desired information! :rocket:

**Pull request merged**
